version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/meubanco
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
